name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{cpp, h, hpp} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Install ncurses
        run: sudo apt-get install -y libncurses5-dev libncursesw5-dev

      - name: Build application
        run: make

      - name: Check test
        run: make test